// ============================================
// Workflows: Screening (Step 1-4) & Alpha Tracking
// ============================================

import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from 'cloudflare:workers';
import type { D1Database } from '@cloudflare/workers-types';
import { JQuantsClient } from './api/jquants';
import { YahooFinanceClient } from './api/yahoo-finance';
import { EdinetClient } from './api/edinet';
import { OpenRouterClient } from './api/openrouter';
import { ScreenerDB } from './db/schema';
import type {
  ScreeningWorkflowParams,
  AlphaTrackingParams,
  QuantScreenedStock,
  LlmEvaluation,
} from './types';

// --- Env type (generated by wrangler types) ---
interface Env {
  DB: D1Database;
  JQUANTS_API_KEY: string;
  EDINET_SUBSCRIPTION_KEY: string;
  OPENROUTER_API_KEY: string;
  JQUANTS_API_BASE: string;
  EDINET_API_BASE: string;
  OPENROUTER_API_BASE: string;
}

/** Step 2 用: 評価が必要な銘柄 */
interface EvaluationNeeded {
  stock: QuantScreenedStock;
  doc: { docId: string; submittedDate: string } | null;
}

/** Step 3 用: 評価結果付き銘柄 */
interface EvaluatedStock {
  stock: QuantScreenedStock;
  eval: LlmEvaluation;
  docId: string;
  submittedDate: string;
}

// ============================================
// Screening Workflow
// ============================================
export class ScreeningWorkflowV2 extends WorkflowEntrypoint<Env, ScreeningWorkflowParams> {
  async run(event: WorkflowEvent<ScreeningWorkflowParams>, step: WorkflowStep) {
    const dryRun = event.payload.dryRun ?? false;
    const db = new ScreenerDB(this.env.DB);

    // --- Step 1: J-Quants 定量スクリーニング ---
    const jquants = new JQuantsClient(
      this.env.JQUANTS_API_KEY,
      this.env.JQUANTS_API_BASE
    );
    const edinet = new EdinetClient(
      this.env.EDINET_API_BASE,
      this.env.EDINET_SUBSCRIPTION_KEY
    );

    const screened = await step.do(
      'step1-quantitative-screening-v2',
      {
        retries: { limit: 3, delay: '120 seconds', backoff: 'exponential' },
        timeout: '30 minutes',
      },
      async () => {
        console.log('Step 1: 定量スクリーニング開始');
        const stocks = await jquants.screenQuantitatively(edinet, db);
        if (stocks.length === 0) {
          console.log('Step 1: スクリーニング対象なし。終了します。');
          return [];
        }
        console.log(`Step 1: ${stocks.length}銘柄が定量基準を満たしました`);
        return stocks;
      }
    );

    console.log(`Step1: ${screened.length} stocks passed quantitative screening`);

    if (screened.length === 0) {
      console.log('No stocks passed screening. Ending workflow.');
      return { passed: 0, picked: 0 };
    }

    // --- Step 2: D1 キャッシュ確認 ---
    const toEvaluate = await step.do(
      'step2-check-cache-v2',
      {
        retries: { limit: 3, delay: '10 seconds', backoff: 'linear' },
        timeout: '5 minutes',
      },
      async () => {
        console.log(`Step 2: Processing ${screened.length} screened stocks`);
        console.log(`Step 2: EDINET_API_BASE=${this.env.EDINET_API_BASE}`);
        console.log(`Step 2: EDINET_SUBSCRIPTION_KEY=${this.env.EDINET_SUBSCRIPTION_KEY ? 'set' : 'not set'}`);
        
        const edinet = new EdinetClient(
          this.env.EDINET_API_BASE,
          this.env.EDINET_SUBSCRIPTION_KEY
        );

        // Test D1 connection
        try {
          const testMapping = await db.getEdinetMapping('21730');
          console.log(`Step 2: D1 test mapping for 21730: ${testMapping ? JSON.stringify(testMapping) : 'null'}`);
        } catch (err) {
          console.error(`Step 2: D1 test failed:`, err);
        }

        // Test EDINET API directly
        try {
          const testDocs = await edinet.fetchLatestYukashokenReports('21730', '博展', 'E05737');
          console.log(`Step 2: EDINET test for 21730: ${testDocs.length} docs found`);
          if (testDocs.length > 0) {
            console.log(`Step 2: EDINET test doc: ${testDocs[0].docID}`);
          }
        } catch (err) {
          console.error(`Step 2: EDINET test failed:`, err);
        }

        const needed: EvaluationNeeded[] = [];

        for (const stock of screened) {
          console.log(`Step 2: Checking stock ${stock.code} ${stock.name}`);
          
          try {
            // EDINETコードマッピングを確認
            const mapping = await db.getEdinetMapping(stock.code);
            const edinetCode = mapping?.edinet_code;
            console.log(`Step 2: Mapping for ${stock.code}: edinetCode=${edinetCode || 'none'}`);
            
            // 最新の有価証券報告書を取得
            const docs = await edinet.fetchLatestYukashokenReports(stock.code, stock.name, edinetCode);
            console.log(`Step 2: Found ${docs.length} docs for ${stock.code}`);
            const latestDoc = docs[0];

            if (!latestDoc) {
              console.log(`Step 2: No documents found for ${stock.code}, skipping`);
              continue;
            }
            console.log(`Step 2: Latest doc for ${stock.code}: ${latestDoc.docID} (${latestDoc.docDescription})`);

            const submittedDate = latestDoc.submitDateTime.slice(0, 10);
            const cached = await db.getEvaluationByDocId(stock.code, latestDoc.docID);
            console.log(`Step 2: Cache check for ${stock.code}: ${cached ? 'found' : 'not found'}`);

            if (cached && cached.submitted_date === submittedDate) {
              console.log(`Cache hit: ${stock.code} doc=${latestDoc.docID}`);
              continue;
            }

            needed.push({
              stock,
              doc: { docId: latestDoc.docID, submittedDate },
            });
            console.log(`Step 2: Added ${stock.code} to evaluation queue`);
          } catch (err) {
            console.error(`Step 2: Error processing ${stock.code}:`, err);
          }
        }

        console.log(`Step 2: ${needed.length} stocks need LLM evaluation`);
        return needed;
      }
    );

    console.log(`Step2: ${toEvaluate.length} stocks need LLM evaluation`);

    // --- Step 3: EDINET + LLM 定性評価 ---
    const evaluated: EvaluatedStock[] = [];

    // 並列制御: Free tier リソース制限を考慮し、バッチ処理
    const BATCH_SIZE = 3;
    for (let i = 0; i < toEvaluate.length; i += BATCH_SIZE) {
      const batch = toEvaluate.slice(i, i + BATCH_SIZE);

      const batchResults = await Promise.all(
        batch.map((item) =>
          step.do(
            `step3-llm-eval-v2-${item.stock.code}`,
            {
              retries: { limit: 3, delay: '20 seconds', backoff: 'exponential' },
              timeout: '5 minutes',
            },
            async () => {
              if (!item.doc) throw new Error(`Missing doc for ${item.stock.code}`);

              const edinet = new EdinetClient(
                this.env.EDINET_API_BASE,
                this.env.EDINET_SUBSCRIPTION_KEY
              );
              const openrouter = new OpenRouterClient(
                this.env.OPENROUTER_API_KEY,
                this.env.OPENROUTER_API_BASE
              );

              // EDINETから書類テキストをストリーミング取得（128MB対応）
              const docText = await edinet.fetchDocumentText(item.doc.docId);

              // LLM評価
              const evalResult = await openrouter.evaluateCompany(docText);

              return {
                stock: item.stock,
                eval: evalResult,
                docId: item.doc.docId,
                submittedDate: item.doc.submittedDate,
              };
            }
          )
        )
      );

      evaluated.push(...batchResults);
    }

    console.log(`Step3: ${evaluated.length} stocks evaluated by LLM`);

    // --- Step 4: D1 保存 & Pick 選定 ---
    const picked = await step.do(
      'step4-save-and-pick-v2',
      {
        retries: { limit: 3, delay: '10 seconds', backoff: 'linear' },
        timeout: '5 minutes',
      },
      async () => {
        let count = 0;

        for (const item of evaluated) {
          // キャッシュ保存
          await db.insertEvaluation(
            item.stock.code,
            item.docId,
            item.submittedDate,
            item.eval.is_owner_company,
            item.eval.management_score,
            item.eval.reason
          );

          // 選定基準:
          // - オーナー企業
          // - 経営スコア >= 60
          // - 実質PER <= 10
          if (
            item.eval.is_owner_company &&
            item.eval.management_score >= 60 &&
            item.stock.realPER <= 10
          ) {
            if (!dryRun) {
              await db.upsertPick({
                code: item.stock.code,
                name: item.stock.name,
                marketCap: item.stock.marketCap,
                netCash: item.stock.netCash,
                realPER: item.stock.realPER,
                salesGrowth3Y: item.stock.salesGrowth3Y,
                profitGrowth3Y: item.stock.profitGrowth3Y,
                isOwnerCompany: item.eval.is_owner_company,
                managementScore: item.eval.management_score,
                latestPrice: item.stock.latestPrice,
                latestTopix: item.stock.latestTopix,
                kiyoharaCompliant: true,
                reason: item.eval.reason,
                netCashRatio: (item.stock as any).netCashRatio ?? 0,
              });
            }
            count++;
          }
        }

        return count;
      }
    );

    console.log(`Step4: ${picked} stocks picked`);

    return { passed: screened.length, evaluated: evaluated.length, picked };
  }
}

// ============================================
// Alpha Tracking Workflow
// ============================================
export class AlphaTrackingWorkflow extends WorkflowEntrypoint<Env, AlphaTrackingParams> {
  async run(event: WorkflowEvent<AlphaTrackingParams>, step: WorkflowStep) {
    const targetDate = event.payload.date ?? new Date().toISOString().slice(0, 10);
    const db = new ScreenerDB(this.env.DB);

    const activePicks = await step.do('fetch-active-picks', async () => db.getActivePicks());
    if (activePicks.length === 0) {
      console.log('No active picks to track.');
      return { tracked: 0 };
    }

    const yahoo = new YahooFinanceClient();

    // 最新TOPIX
    const topixPrice = await step.do('fetch-topix', { retries: { limit: 3, delay: '10 seconds' } }, async () => {
      return await yahoo.fetchTopix();
    });

    if (!topixPrice) {
      throw new Error('Failed to fetch TOPIX price');
    }

    // 各銘柄の最新株価を取得
    const prices = await step.do(
      'fetch-stock-prices',
      { retries: { limit: 3, delay: '10 seconds' }, timeout: '15 minutes' },
      async () => {
        const results: { code: string; price: number }[] = [];
        for (const pick of activePicks) {
          try {
            const quote = await yahoo.fetchQuote(pick.code);
            if (quote?.close) {
              results.push({ code: pick.code, price: quote.close });
            }
          } catch (err) {
            console.warn(`Failed to fetch price for ${pick.code}:`, err);
          }
        }
        return results;
      }
    );

    // Alpha計算 & D1保存
    const tracked = await step.do('calculate-and-save-alpha', async () => {
      const trackingRows: Parameters<typeof db.batchInsertTracking>[0] = [];

      for (const p of prices) {
        const pick = activePicks.find((ap) => ap.code === p.code);
        if (!pick || !pick.initial_price || !pick.initial_topix) continue;

        const stockReturn = (p.price - pick.initial_price) / pick.initial_price;
        const topixReturn = (topixPrice - pick.initial_topix) / pick.initial_topix;
        const alpha = (stockReturn - topixReturn) * 100; // %

        // 累積Alpha: 前日の累積 + 当日Alpha（簡易版: 選定時からの累積を再計算）
        const cumulativeAlpha = alpha;

        trackingRows.push({
          code: p.code,
          date: targetDate,
          price: p.price,
          topix: topixPrice,
          alpha,
          cumulative_alpha: cumulativeAlpha,
        });
      }

      await db.batchInsertTracking(trackingRows);
      return trackingRows.length;
    });

    console.log(`Alpha tracking completed for ${tracked} stocks on ${targetDate}`);
    return { tracked };
  }
}
